# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 819443f5ddb5aac69ca2729638f2ecdfe04622c4800a9c31bc7e2d038c951de427bab070556ea457be6f9f6d4cceea058dd734eebc8df1f4b485b1d2a5ae5730

test:
  secret_key_base: 6c399024d78f2614ebe03dc4d4830808d7b476c0f99d969e2595fa496f8bc7fb3476f97510b5f507e474c41cd26892c8e1b2cd3743cae966e459c562aa754576

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
